#!/bin/sh

echo "Starting mender wrapper"

# Did the user specify standalone install mode?
echo $@ | grep ' install \| -install ' > /dev/null
if [ $? -eq 0 ]; then
    install_arg=true
    # Exit with failure and error message if we don't have alignment
    # between boot slot and rootfs.  It's not safe to update in this case
    /etc/mender/verify-boot-rootfs-slot-alignment-uboot || exit 1
fi

# Call the base mender executable, renamed
mender_override $@

rc=$?
if [ $rc -eq 0 ]; then
    if [ "$install_arg" = true ]; then
        # Add a marker to show update was successful, for auto-commit script
        touch /var/lib/mender/mender-install-success
    fi
fi
